### ISSUE TITLE
ROAD MAP TO PRE-ALPHA

### ISSUE THREAD

**Issue by lilbentley** [lilbentley/lilbentley.github.io#1]
### Prerequisits for having a working shareable version:

- [ ] LOADING SCREEN
- [ ] LOWPOLY SCENE (under 5k + single material)
- [ ] DEVICE SIZE DETECTION + CAMERA/REMOTE DEPENDENCY ON SCREEN SIZE
- [ ] RESPONSIVE TO MOUSE IN INITIAL STATE (FPS-que movement)
- [ ] INTERACTIVE GADGET (optional)
